declare const styles: {
  readonly eyebrow: string;
  readonly eyebrowLabel: string;
  readonly eyebrowMeta: string;
  readonly eyebrowOverline: string;
  readonly eyebrowSection: string;
  readonly heading: string;
  readonly headingContent: string;
  readonly headingDisplay: string;
  readonly headingItem: string;
  readonly headingModule: string;
  readonly headingSection: string;
  readonly measureLg: string;
  readonly measureMd: string;
  readonly measureSm: string;
  readonly text: string;
  readonly textBody: string;
  readonly textDetail: string;
  readonly textLead: string;
  readonly textQuote: string;
  readonly textSupporting: string;
  readonly toneAccent: string;
  readonly toneDefault: string;
  readonly toneInherit: string;
  readonly toneInverse: string;
  readonly toneSubdued: string;
};
export = styles;
